name: Build Custom Docker Image

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "SOURCE_IMAGE=ghcr.io/this-is-tobi/mirror/mattermost" >> $GITHUB_ENV
          echo "MM_DIRECTORY=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Get latest tag from source image
        id: get_latest_tag
        run: |
          echo "Fetching the latest tag for $SOURCE_IMAGE..."
          LATEST_TAG=$(curl -s "https://ghcr.io/v2/this-is-tobi/mirror/mattermost/tags/list" \
                          | jq -r '.tags | map(select(test("^\\d+\\.\\d+\\.\\d+$"))) | sort | last')
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Build custom Docker image
        run: |
          echo "Building custom Docker image with tag: ${{ env.latest_tag }}"
          docker build -t yawlmost:${{ env.latest_tag }} $MM_DIRECTORY

      - name: Push custom Docker image
        run: |
          echo "Pushing custom Docker image yawlmost:${{ env.latest_tag }}"
          echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push yawlmost:${{ env.latest_tag }}