name: Get Docker Image Tags

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  get_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "REPO=ghcr.io/this-is-tobi/mirror/mattermost" >> $GITHUB_ENV
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Get latest tag from GHCR
        id: get_latest_tag
        run: |
          echo "Fetching the latest tag for $REPO..."
          token=$(curl -s "https://ghcr.io/token?service=ghcr.io&scope=repository:${{ env.REPO }}:pull" \
                       -u "${{ github.actor }}:${{ secrets.GH_TOKEN }}" \
                  | jq -r '.token')

          latest_tag=$(curl -H "Authorization: Bearer $token" \
                           -s "https://ghcr.io/v2/${{ env.REPO }}/tags/list" | \
                           jq -r '.tags | map(select(test("^\\d+\\.\\d+\\.\\d+$"))) | sort | last')
          
          if [ -z "$latest_tag" ]; then
            echo "No valid tags found."
            exit 1
          fi

          echo "Latest tag is $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Use the latest tag
        run: |
          echo "The latest Docker image tag is: ${{ env.latest_tag }}"
          # You can add further steps here to use the latest tag