name: Build and Publish Custom Mattermost Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest tag of source image
        id: get_tag
        run: |
          SOURCE_IMAGE="ghcr.io/this-is-tobi/mirror/mattermost"
          LATEST_TAG=$(curl -s "https://ghcr.io/v2/this-is-tobi/mirror/mattermost/tags/list" | jq -r '.tags | map(select(test("^\\d+\\.\\d+\\.\\d+$"))) | sort | last')
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Check if tag has changed
        id: check
        run: |
          if [ "$LATEST_TAG" == "$(cat .latest_tag 2>/dev/null)" ]; then
            echo "No new version detected. Skipping build."
            exit 0
          fi
          echo "$LATEST_TAG" > .latest_tag

      - name: Build custom Docker image
        if: steps.check.outcome == 'failure'
        run: |
          docker build -t ghcr.io/${{ github.repository }}/custom-mattermost:$LATEST_TAG --build-arg BASE_IMAGE=ghcr.io/this-is-tobi/mirror/mattermost:$LATEST_TAG .

      - name: Push Docker image to GitHub Container Registry
        if: steps.check.outcome == 'failure'
        run: |
          docker push ghcr.io/${{ github.repository }}/custom-mattermost:$LATEST_TAG